<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRvaoiai\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRvaoiai/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRvaoiai.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRvaoiai\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRvaoiai\appProdProjectContainer(array(
    'container.build_hash' => 'Rvaoiai',
    'container.build_id' => '22792b74',
    'container.build_time' => 1538255348,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRvaoiai');
